[features]
seeds = false
skip-lint = false

[programs.localnet]
stache = "71KtSAv6Qtpa2AZAwDhipKeoiCoyUXKbLpNheTJUGW8B"

[programs.devnet]
stache = "71KtSAv6Qtpa2AZAwDhipKeoiCoyUXKbLpNheTJUGW8B"

[programs.mainnet]
stache = "71KtSAv6Qtpa2AZAwDhipKeoiCoyUXKbLpNheTJUGW8B"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
